#!/usr/bin/env python
import os
import sipconfig

basename = "crowdsight"

# The name of the SIP build file generated by SIP and used by the build
# system.
build_dir = 'build'
build_file = os.path.join(build_dir, basename + ".sbf")

# Get the SIP configuration information.
config = sipconfig.Configuration()

if not os.path.isdir(build_dir):
    os.makedirs(build_dir)

# Run SIP to generate the code.
os.system(" ".join([config.sip_bin, "-g", "-c", build_dir, "-b", build_file, basename + ".sip"]))

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file, makefile=os.path.join(build_dir, 'Makefile'))

# Add the library we are wrapping.  The name doesn't include any platform
# specific prefixes or extensions (e.g. the "lib" prefix on UNIX, or the
# ".dll" extension on Windows).
makefile.extra_libs = [basename]

# Search libraries in current directory
#makefile.extra_lflags= ['-L.']

# Generate the Makefile itself.
makefile.generate()
